sonar.projectKey=Iftekhar13_SIT753-Jenkins
sonar.organization=iftekhar13
sonar.host.url=https://sonarcloud.io

sonar.projectName=Book Catalogue

sonar.sources=server.js,routes,controllers,models,services,public
sonar.tests=tests

sonar.exclusions=node_modules/**,release/**,coverage/**,.git/**,.scannerwork/**
sonar.sourceEncoding=UTF-8