sonar.projectKey=Iftekhar13_SIT753-Jenkins
sonar.organization=iftekhar13
sonar.host.url=https://sonarcloud.io

sonar.projectName=Book Catalogue
sonar.sources=.
sonar.exclusions=node_modules/**,release/**,coverage/**,.git/**

sonar.tests=tests
sonar.sourceEncoding=UTF-8